#!/bin/bash

if [ ! $# -eq 4 ];
then
  echo "usage : $0 <local> <remote> <base> <merged>"
  exit -1
fi

tmp=$(mktemp -d)
cp $3 $tmp

LOCAL=$1
REMOTE=$2
BASE=$(ls $tmp/*)
MERGED=$4

echo $BASE
base_creation=$(stat -c %Y $BASE)
meld --diff $LOCAL $MERGED $REMOTE --diff $LOCAL $BASE $REMOTE
meld_exit_code=$?

base_modif=$(stat -c %Y $BASE)
merged_modif=$(stat -c %Y $MERGED)

if [ $base_modif -gt $base_creation ] && [ $base_modif -gt $merged_modif ] 
then

  if whiptail --yesno "The common ancestor has been edited, do you want to use it as the result of the merge ?" 20 60 ;then
    cp $BASE $MERGED
  fi

fi

rm -r $tmp
